### ISSUE TITLE
Durability doc is out of date

### ISSUE THREAD

**Issue by WilliamParker** [oracle-samples/clara-site#11]
Basically the same issue as https://github.com/cerner/clara-examples/issues/8

I propose removing the existing durability documentation and replacing it once we have documentation of the new API.

**Comment by mrrodriguez** [comment]
I wouldn't mind doing this one. I was planning to get to it soon. I'd say within this week.

**Comment by mrrodriguez** [comment]
Just an update, I'm still working on getting this done.

**Comment by WilliamParker** [comment]
I went ahead and removed the existing doc and replaced it with a note that documentation of the new API is pending and a link to the GitHub issue.  That deletion shouldn't make adding new doc any harder and the APIs are so different that the existing doc is just misinformation that we're better off without, even with no immediate replacement.

PR: https://github.com/cerner/clara-site/pull/18

**Comment by mrrodriguez** [comment]
Thanks @WilliamParker I'll try to get to a PR for this soon.  I got a little more delayed than expected.

**Comment by mrrodriguez** [comment]
#20 is my first pass at this.  If it hangs open for a while, I may still edit it some.  However, I think it may be acceptable as a first pass.

**Comment by WilliamParker** [comment]
The commit https://github.com/cerner/clara-site/commit/44a6d9aca085a46adc2ab9ec04334c5a3cd3d94b in the gh-pages branch is a manual merge of https://github.com/cerner/clara-site/pull/20.

I don't see anything left to do on this issue.  I'm going to close it and we can reopen it if anyone disagrees.  Thanks @mrrodriguez .
