### ISSUE TITLE
Remove "(In progress)" from repo subtitle?

### ISSUE THREAD

**Issue by alex-dixon** [oracle-samples/clara-site#25]
The subtitle for the Github repo shows "Clara Web Site (In Progress)". Is it ok to remove "(In Progress)" at this point?

**Comment by WilliamParker** [comment]
At this point I think the docs are mature enough that we can do so.  Objections anyone?

**Comment by WilliamParker** [comment]
"Objections anyone?"

After 26 days I'm going to take that as a no.
I have made the change, closing issue.
