### ISSUE TITLE
Windspeeds example uses invalid syntax

### ISSUE THREAD

**Issue by alex-dixon** [oracle-samples/clara-site#26]
Colin pointed out this example is not valid Clara syntax:
https://github.com/cerner/clara-site/blob/07b1a4dd963e097e85b1d28e84f4a444c98e3eb5/_docs/usingaccumulators.md#L28

Should be `[?temp <- Temperature (= ?location location)]`.  With the square brackets it throws an "extraneous brackets" error.

**Comment by WilliamParker** [comment]
Any objections to closing this @alex-dixon ?  It looks like https://github.com/cerner/clara-site/pull/27 addressed the issue.

**Comment by alex-dixon** [comment]
No sir. Thank you.
