### ISSUE TITLE
Documentation of keyword boolean operators

### ISSUE THREAD

**Issue by WilliamParker** [oracle-samples/clara-site#6]
The behavior of boolean conditions that are reflected in the compiled Rete network
 (i.e. that use the keyword boolean operators) has been a source of confusion on our team.
 For example, to reuse an example from clara-site,

```
 [:or [Customer (= status :vip)]
     [Promotion (= type :discount-month)]]
```

this is not a short-circuiting Clojure or and will result in a rule activation for a satisfying Promotion
regardless of whether a satisfying Customer is also in the session.  Conversely, something like

```
[Customer (or (= status :vip) (= type :long-term-customer))]
```

will not fire twice for a single Customer that meets both conditions.

I think it would be helpful to have some more elaboration in clara-site on this point, possibly
in a more detailed subpage on boolean expressions than is present at http://www.clara-rules.org/docs/expressions/ currently
as well as some usage of them in the clara-examples project. I currently only see usage of the not operator.  (I'm willing to add this doc if this sounds like something you agree should be added.)

**Comment by rbrush** [comment]
Good points. Looking at it now the documentation in this space is pretty weak. I'd be happy to merge anything in this space if you do want to expand it.

**Comment by WilliamParker** [comment]
I added a pull request for some examples of this in clara-examples at https://github.com/rbrush/clara-examples/pull/7

I'll plan to add something on the topic to clara-site in another pull request.

**Comment by rbrush** [comment]
Sounds good! (The clara-example updates have been merged.)

**Comment by WilliamParker** [comment]
I have created a pull request for the clara-site update:
https://github.com/rbrush/clara-site/pull/7

I decided to add the new docs to a separate page linked to by the main "Expressions" page since those updates are longer and my guess is that using Rete boolean expressions is a minority use case.  I can change it to all be inline in the main "Expressions" page if you'd prefer though.

**Comment by WilliamParker** [comment]
I don't see anything further to do here now that both the clara-examples and clara-site changes have been merged so I'm closing this issue.
